{{- if .Values.keyVault.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.keyVault.serviceAccountName }}
  labels:
    {{- include "cnip.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.keyVault.workloadIdentityClientId | quote }}
{{- end }}
